/**
 * Real document lists pulled from taxdeed.duvalclerk.com on 2026-08-27, for the
 * five cases acquisitions worked by hand and wrote up. Kept verbatim, typos and
 * all, because the typos are load bearing: Duval ships "Undelieverd",
 * "Undelievered" and "Undelivered" on the same docket.
 *
 * These are the regression suite for surplus-classify.util.ts. If a classifier
 * change moves any of these five verdicts, the change is wrong until proven
 * otherwise.
 */

/** 2026-0004TD, $22,421.18, Duval id 5037. Notice mailed, nothing filed. */
export const DANNIE_STEWART = {
  caseNumber: "2026-0004TD",
  sourceCaseId: "5037",
  surplus: "$22,421.18",
  owners: ["DANNIE LESTER STEWART", "DANNIE LESTER STEWART ESTATE"],
  docs: [
    "DR-512",
    "DR-513",
    "OEReportDocuments",
    "OEReportTitleExpress",
    "Receipt",
    "Property Appraiser Information Sheet",
    "Tax Record",
    "Cost Statement",
    "Recorded Notice of Application",
    "Receipt",
    "Notice Of Application Publisher",
    "Notice Of Application",
    "Return of Service from Sheriff's Office",
    "Return of Service from Sheriff's Office",
    "Additional Taxes",
    "DR Invoice",
    "Regular Mail Undelievered",
    "Regular Mail Undelievered",
    "Regular Mail Undelievered",
    "Receipt",
    "Tax Deed",
    "Proof of Publication",
    "Notice Of Surplus Funds",
    "Regular Mail Undelievered",
    "Regular Mail Undelievered",
    "Certified Mail Undelivered",
    "Certified Mail Undelivered",
    "RealAuction Payment Receipt",
    "Verification",
    "Applicant Disbursement",
  ],
};

/** 2025-0829TD, $12,445.68, Duval id 5012. Ad valorem homestead lien only. */
export const ELLA_CLOWERS = {
  caseNumber: "2025-0829TD",
  sourceCaseId: "5012",
  surplus: "$12,445.68",
  owners: ["EDGAR CLOWERS, JR."],
  docs: [
    "DR-512",
    "DR-513",
    "OEReportDocuments",
    "OEReportTitleExpress",
    "Receipt",
    "Property Appraiser Information Sheet",
    "Tax Record",
    "Cost Statement",
    "Notice Of Application Publisher",
    "Recorded Notice of Application",
    "Receipt",
    "Return of Service from Sheriff's Office",
    "Return of Service from Sheriff's Office",
    "Notice Of Application",
    "Additional Taxes",
    "Returned Not Served Sheriff Notice",
    "DR Invoice",
    "Certified Mail Undelieverd",
    "Certified Mail Undelieverd",
    "Certified Mail Undelieverd",
    "Notice Of Application Publisher",
    "DR Invoice-Resale",
    "Receipt",
    "Surplus - Ad Valorem Homestead Liens",
    "Notice Of Surplus Funds",
    "Tax Deed",
    "Proof of Publication",
    "Tax Collector Disbursement",
    "RealAuction Payment Receipt",
    "Communication",
    "Applicant Disbursement",
    "Regular Mail Delivered",
  ],
};

/** 2025-0761TD, $40,091.71, Duval id 4944. Two claims, both denied. */
export const LINDA_SHIRLEY = {
  caseNumber: "2025-0761TD",
  sourceCaseId: "4944",
  surplus: "$40,091.71",
  owners: ["LINDA L. SHIRLEY"],
  docs: [
    "DR-512",
    "DR-513",
    "OEReportDocuments",
    "OEReportTitleExpress",
    "Property Appraiser Information Sheet",
    "Tax Record",
    "Receipt",
    "Cost Statement",
    "Notice Of Application Publisher",
    "Recorded Notice of Application",
    "Receipt",
    "Return of Service from Sheriff's Office",
    "Return of Service from Sheriff's Office",
    "Notice Of Application",
    "Additional Taxes",
    "DR Invoice",
    "Receipt",
    "Tax Deed",
    "Proof of Publication",
    "Notice Of Surplus Funds",
    "Tax Collector Disbursement",
    "Surplus - Submitted Claim",
    "Denial Letter",
    "Surplus - Submitted Claim",
    "Denial Letter",
    "RealAuction Payment Receipt",
    "Applicant Disbursement",
    "Photo IDs for Surplus Claims",
    "Probate Documents",
    "Notary Verification",
  ],
};

/** 2025-0732TD, $42,527.23, Duval id 4915. One claim pending, claimant not named in the record. */
export const SUSAN_WRIGHT = {
  caseNumber: "2025-0732TD",
  sourceCaseId: "4915",
  surplus: "$42,527.23",
  owners: ["SUSAN D WRIGHT"],
  docs: [
    "DR-512",
    "DR-513",
    "OEReportDocuments",
    "OEReportTitleExpress",
    "Property Appraiser Information Sheet",
    "Tax Record",
    "Receipt",
    "SunBiz",
    "Cost Statement",
    "Notice Of Application Publisher",
    "Recorded Notice of Application",
    "Receipt",
    "Return of Service from Sheriff's Office",
    "Return of Service from Sheriff's Office",
    "Notice Of Application",
    "Additional Taxes",
    "DR Invoice",
    "Certified Mail Undelieverd",
    "Receipt",
    "Tax Deed",
    "Proof of Publication",
    "Notice Of Surplus Funds",
    "Tax Collector Disbursement",
    "Regular Mail Undelievered",
    "Regular Mail Undelievered",
    "Surplus - Submitted Claim",
    "RealAuction Payment Receipt",
    "Applicant Disbursement",
    "Photo IDs for Surplus Claims",
    "Photo IDs for Surplus Claims",
    "Notary Verification",
  ],
};

/** 2025-0774TD, $27,929.98, Duval id 4957. Four claims, one denial, then paid out. */
export const KENNETH_PEEPLES = {
  caseNumber: "2025-0774TD",
  sourceCaseId: "4957",
  surplus: "$27,929.98",
  owners: ["KENNETH PEEPLES"],
  docs: [
    "DR-512",
    "DR-513",
    "OEReportDocuments",
    "OEReportTitleExpress",
    "Receipt",
    "Property Appraiser Information Sheet",
    "Tax Record",
    "Cost Statement",
    "Notice Of Application Publisher",
    "Recorded Notice of Application",
    "Receipt",
    "Returned Not Served Sheriff Notice",
    "Return of Service from Sheriff's Office",
    "Returned Not Served Sheriff Notice",
    "Returned Not Served Sheriff Notice",
    "Notice Of Application",
    "Additional Taxes",
    "DR Invoice",
    "Certified Mail Undelieverd",
    "Certified Mail Undelieverd",
    "Receipt",
    "RealAuction Payment Receipt",
    "Tax Deed",
    "Proof of Publication",
    "Notice Of Surplus Funds",
    "Tax Collector Disbursement",
    "Regular Mail Undelievered",
    "Regular Mail Undelievered",
    "Surplus - Submitted Claim",
    "Denial Letter",
    "Surplus - Submitted Claim",
    "Surplus - Submitted Claim",
    "Surplus - Submitted Claim",
    "Surplus Distribution",
    "Surplus Distribution",
    "Surplus Distribution",
    "Applicant Disbursement",
    "Notary Verification",
    "Photo IDs for Surplus Claims",
    "Notary Verification",
    "Notary Verification",
    "Probate Documents",
    "Verification",
    "Verification",
    "Verification",
    "Notary Verification",
    "Communication",
    "Surplus Breakdown",
  ],
};

